- name: Remove matrix user and group
  hosts: slurmctld_host,slurmd_host,slurm-lab-client
  tasks:
    - name: Ensure user smith, trinity, neo absent
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
        remove: true
      loop:
        - smith
        - trinity
        - neo

    - name: Ensure group matrix absent
      ansible.builtin.group:
        name: matrix
        state: absent
