- hosts: slurmctld_host,slurmd_host,slurm-lab-client
  tasks:
      - name: ensure user smith, trinity, neo absent
        user:
          name: "{{ item }}"
          state: absent
          remove: true
        loop:
          - smith
          - trinity
          - neo
          
      - name: ensure group matrix absent
        group:
          name: matrix
          state: absent