- name: Create user smith
  hosts: slurmctld_host,slurmd_host,slurm-lab-client
  tasks:
    - name: Ensure group matrix exist
      ansible.builtin.group:
        name: matrix

    - name: Ensure user smith exist
      ansible.builtin.user:
        name: smith
        group: matrix
        generate_ssh_key: true

- name: Create user trinity
  hosts: slurmctld_host,slurm-lab-client
  tasks:
    - name: Ensure group matrix exist
      ansible.builtin.group:
        name: matrix

    - name: Ensure user trinity exist
      ansible.builtin.user:
        name: trinity
        group: matrix
        generate_ssh_key: true

- name: Create user neo
  hosts: slurm-lab-client
  tasks:
    - name: Ensure group matrix exist
      ansible.builtin.group:
        name: matrix

    - name: Ensure user neo exist
      ansible.builtin.user:
        name: neo
        group: matrix
        generate_ssh_key: true
