- name: Configure slurm to use munge authentication plugin
  hosts: slurmctld_host,slurmd_host,slurm-lab-client
  tasks:
    - name: Modify slurmdbd.conf
      ansible.builtin.lineinfile:
        path: /etc/slurm/slurmdbd.conf
        backup: true
        regexp: "{{ item.param }}="
        line: "{{ item.param }}={{ item.value }}"
      loop:
        - param: AuthType
          value: auth/slurm
        - param: AuthInfo
          value: use_client_ids
      notify:
        - Restart-slurmdb

    - name: Modify slurm.conf
      ansible.builtin.lineinfile:
        path: /etc/slurm/slurm.conf
        backup: true
        regexp: "{{ item.param }}="
        line: "{{ item.param }}={{ item.value }}"
      loop:
        - param: AuthType
          value: auth/slurm
        - param: CredType
          value: cred/slurm
        - param: AuthInfo
          value: use_client_ids
      notify:
        - Restart-slurmctld
        - Restart-slurmd
        - Restart-sackd

    - name: Stop munge
      ansible.builtin.systemd_service:
        name: munge
        state: stopped
        enabled: false

  handlers:
    - name: Restart-slurmdb
      ansible.builtin.systemd_service:
        name: slurmdbd
        state: restarted
      when: "'slurmctld_host' in group_names"

    - name: Restart-slurmctld
      ansible.builtin.systemd_service:
        name: slurmctld
        state: restarted
      when: "'slurmctld_host' in group_names"

    - name: Restart-slurmd
      ansible.builtin.systemd_service:
        name: slurmd
        state: restarted
      when: "'slurmd_host' in group_names"

    - name: Restart-sackd
      ansible.builtin.systemd_service:
        name: slurmd
        state: restarted
      when: "'slurmd_host' not in group_names and 'slurmctld_host' not in group_names"
