FROM docker.io/library/maven:3.8.7-openjdk-18-slim AS key-generator
COPY json-web-key-generator /build
WORKDIR /build
# Build the app
# Artifact will be stored at /build/target/json-web-key-generator-0.9-SNAPSHOT-jar-with-dependencies.jar
RUN mvn package
RUN java -jar /build/target/json-web-key-generator-0.9-SNAPSHOT-jar-with-dependencies.jar --type RSA --size 2048 --algorithm RS256 --idGenerator sha1 --keySet --output /jwks.json --pubKeyOutput /jwks.pub.json

FROM quay.io/rockylinux/rockylinux:8 as build-slurm
COPY build-el8/*.sh ./
COPY slurm ./slurm-src
RUN ./build-slurm-rpm.sh

FROM quay.io/rockylinux/rockylinux:8 as build-mpi
COPY --from=build-slurm /opt/slurm-repo /opt/slurm-repo
COPY --from=build-slurm /etc/yum.repos.d/slurm.repo /etc/yum.repos.d/slurm.repo
COPY mpich ./mpich-src
COPY build-el8/install-packages.sh common/mpich-build.sh ./
RUN ./install-packages.sh
RUN ./mpich-build.sh

FROM quay.io/rockylinux/rockylinux:8
COPY --from=build-slurm /opt/slurm-repo /opt/slurm-repo
COPY --from=build-slurm /etc/yum.repos.d/slurm.repo /etc/yum.repos.d/slurm.repo
COPY --from=build-mpi /opt/mpich /opt/mpich
COPY build-el8/install-packages.sh common/config-task.sh ./
COPY tutorials /etc/skel/tutorials
COPY common/.tmux.conf LICENSE /etc/skel/
COPY common/ssh_config /etc/skel/.ssh/config
COPY common/auto-ssh-keygen.sh /etc/profile.d/
RUN ./install-packages.sh && ./config-task.sh

# slurm related files
COPY common/service-restart.conf /etc/systemd/system/slurmctld.service.d/
COPY common/service-restart.conf /etc/systemd/system/slurmdbd.service.d/
COPY common/service-restart.conf /etc/systemd/system/sackd.service.d/
COPY common/slurmd-extra.conf common/service-restart.conf /etc/systemd/system/slurmd.service.d/
COPY common/slurmrestd-extra.conf common/service-restart.conf /etc/systemd/system/slurmrestd.service.d/
COPY --from=key-generator /jwks.json /jwks.pub.json /etc/slurm/
COPY common/create-account-user.sh /etc/slurm

# Jupyter Hub files
COPY common/jupyterhub_config.py /opt/jupyterhub/etc/jupyterhub/
COPY common/service-restart.conf /etc/systemd/system/jupyter-hub.service.d/
COPY common/proxy.conf /etc/nginx/conf.d/

# Templates
COPY common/*.j2 common/entrypoint.sh /opt/templates/

# ansible inventory
COPY common/ansible.cfg /etc/ansible/ansible.cfg
RUN mkdir -pv /etc/ansible/inventory

# custom services
COPY common/jupyter-hub.service /etc/systemd/system/

# others
COPY common/lyoko.sudo /etc/sudoers.d/lyoko
COPY common/modules /opt/modules
COPY common/module-path.sh /etc/profile.d/z99-module-path.sh
COPY common/jupyter-settings-overrides.json /opt/jupyterhub/share/jupyter/lab/settings/overrides.json
COPY --from=build-slurm /opt/doc /usr/share/nginx/html/doc

RUN create-munge-key \
    && mkdir -pv /var/spool/slurmctld \
    && mkdir -pv /var/spool/slurmd \
    && ln -s /usr/lib/systemd/system/munge.service /etc/systemd/system/multi-user.target.wants/ \
    && rm -f /etc/systemd/system/systemd-logind.service

ENTRYPOINT [ "/opt/templates/entrypoint.sh" ]