# Stage 1: Build Slurm from source
# This stage builds Slurm RPM packages from the source code.
FROM quay.io/rockylinux/rockylinux:8 as build-slurm
# Copy the build scripts and Slurm source code
COPY build-el8/*.sh ./ 
COPY slurm ./slurm-src
# Run the build script to create RPM packages
RUN ./build-slurm-rpm.sh

# Stage 2: Build Open MPI from source
# This stage builds Open MPI, which is required for running MPI jobs with Slurm.
FROM quay.io/rockylinux/rockylinux:8 as build-mpi
# Copy the Slurm repository created in the previous stage
COPY --from=build-slurm /opt/slurm-repo /opt/slurm-repo
COPY --from=build-slurm /etc/yum.repos.d/slurm.repo /etc/yum.repos.d/slurm.repo
# Copy the Open MPI source code and build scripts
COPY ompi ./ompi-src
COPY build-el8/install-packages.sh common/scripts/openmpi-build.sh ./
# Install build dependencies and build Open MPI
RUN ./install-packages.sh
RUN ./openmpi-build.sh

# Final Stage: Create the production image
FROM quay.io/rockylinux/rockylinux:8

# Copy artifacts from previous build stages
COPY --from=build-slurm /opt/slurm-repo /opt/slurm-repo
COPY --from=build-slurm /etc/yum.repos.d/slurm.repo /etc/yum.repos.d/slurm.repo
COPY --from=build-mpi /opt/openmpi /opt/openmpi
COPY --from=build-slurm /opt/doc /usr/share/nginx/html/doc

# Copy scripts and configurations for user environment
COPY build-el8/install-packages.sh common/scripts/config-task.sh ./
COPY tutorials /etc/skel/tutorials
COPY common/.tmux.conf LICENSE /etc/skel/
COPY common/ssh_config /etc/ssh/ssh_config.d/common.conf
COPY common/scripts/auto-ssh-keygen.sh /etc/profile.d/
COPY common/packages.yaml /etc/skel/.spack/packages.yaml 

# Install packages and run initial configuration
RUN ./install-packages.sh && ./config-task.sh

# --- Configure Slurm ---
# Copy systemd service files and configurations for Slurm components
COPY common/systemd/service-restart.conf /etc/systemd/system/slurmctld.service.d/
COPY common/systemd/service-restart.conf /etc/systemd/system/slurmdbd.service.d/
COPY common/systemd/service-restart.conf /etc/systemd/system/sackd.service.d/
COPY common/systemd/slurmd-extra.conf common/systemd/service-restart.conf /etc/systemd/system/slurmd.service.d/
COPY common/systemd/slurmrestd-extra.conf common/systemd/service-restart.conf /etc/systemd/system/slurmrestd.service.d/
# Copy Slurm JWT keys and other secrets
COPY common/secrets/jwks.json common/secrets/jwks.pub.json common/secrets/slurm.jwks /etc/slurm/
# Copy helper scripts
COPY common/scripts/create-account-user.sh /etc/slurm

# --- Configure JupyterHub ---
# Copy JupyterHub configuration and service files
COPY common/jupyterhub_config.py /opt/jupyterhub/etc/jupyterhub/
COPY common/systemd/service-restart.conf /etc/systemd/system/jupyter-hub.service.d/
COPY common/systemd/jupyter-hub.service /etc/systemd/system/
# Copy Nginx proxy configuration for JupyterHub
COPY common/proxy.conf /etc/nginx/conf.d/
# Copy JupyterLab default settings
COPY common/jupyter-settings-overrides.json /opt/jupyterhub/share/jupyter/lab/settings/overrides.json

# --- Configure Ansible ---
COPY common/ansible.cfg /etc/ansible/ansible.cfg
RUN mkdir -pv /etc/ansible/inventory

# --- Other Configurations ---
# Copy templates and entrypoint script
COPY common/templates/*.j2 common/scripts/entrypoint.sh /opt/local/
# Copy sudoers configuration
COPY common/lyoko.sudo /etc/sudoers.d/lyoko
# Copy environment module files
COPY common/modules /opt/modules
# Add module path to shell profile
COPY common/scripts/module-path.sh /etc/profile.d/z99-module-path.sh

# --- Final setup ---
# Create munge key, Slurm spool directories, and enable munge service. 
RUN create-munge-key \
    && mkdir -pv /var/spool/slurmctld \
    && mkdir -pv /var/spool/slurmd \
    && ln -s /usr/lib/systemd/system/munge.service /etc/systemd/system/multi-user.target.wants/ 

# Set the entrypoint for the container
ENTRYPOINT [ "/opt/local/entrypoint.sh" ]
