FROM docker.io/library/maven:3.8.7-openjdk-18-slim AS key-generator
COPY json-web-key-generator /build
WORKDIR /build
# Build the app
# Artifact will be stored at /build/target/json-web-key-generator-0.9-SNAPSHOT-jar-with-dependencies.jar
RUN mvn package
RUN java -jar /build/target/json-web-key-generator-0.9-SNAPSHOT-jar-with-dependencies.jar --type RSA --size 2048 --algorithm RS256 --idGenerator sha1 --keySet --output /jwks.json --pubKeyOutput /jwks.pub.json
RUN java -jar /build/target/json-web-key-generator-0.9-SNAPSHOT-jar-with-dependencies.jar --type oct --size 2048 --algorithm HS256 --idGenerator sha1 --keySet --output /slurm.jwks

FROM docker.io/library/debian:12 as build-slurm
COPY build-deb12/*.sh ./
COPY slurm ./slurm-src
RUN ./build-slurm-deb.sh

FROM docker.io/library/debian:12 as build-mpi
COPY --from=build-slurm /opt/slurm-repo /opt/slurm-repo
COPY --from=build-slurm /etc/apt/sources.list.d/slurm.list /etc/apt/sources.list.d/slurm.list
COPY mpich ./mpich-src
COPY build-deb12/install-packages.sh common/mpich-build.sh ./
RUN ./install-packages.sh
RUN ./mpich-build.sh


FROM docker.io/library/debian:12
COPY --from=build-slurm /opt/slurm-repo /opt/slurm-repo
COPY --from=build-slurm /etc/apt/sources.list.d/slurm.list /etc/apt/sources.list.d/slurm.list
COPY --from=build-mpi /opt/mpich /opt/mpich
COPY build-deb12/install-packages.sh common/config-task.sh ./
COPY tutorials /etc/skel/tutorials
COPY common/.tmux.conf LICENSE /etc/skel/
COPY common/ssh_config /etc/skel/.ssh/config
COPY common/auto-ssh-keygen.sh /etc/profile.d/
RUN ./install-packages.sh && ./config-task.sh

# slurm related files
COPY common/service-restart.conf /etc/systemd/system/slurmctld.service.d/
COPY common/service-restart.conf /etc/systemd/system/slurmdbd.service.d/
COPY common/service-restart.conf /etc/systemd/system/sackd.service.d/
COPY common/slurmd-extra.conf common/service-restart.conf /etc/systemd/system/slurmd.service.d/
COPY common/slurmrestd-extra.conf common/service-restart.conf /etc/systemd/system/slurmrestd.service.d/
COPY --from=key-generator /jwks.json /jwks.pub.json /slurm.jwks /etc/slurm/
COPY common/create-account-user.sh /etc/slurm

# Jupyter Hub files
COPY common/jupyterhub_config.py /opt/jupyterhub/etc/jupyterhub/
COPY common/service-restart.conf /etc/systemd/system/jupyter-hub.service.d/
COPY common/proxy.conf /etc/nginx/sites-available/default

# Templates
COPY common/*.j2 common/entrypoint.sh /opt/local/

# ansible inventory
COPY common/ansible.cfg /etc/ansible/ansible.cfg
RUN mkdir -pv /etc/ansible/inventory

# custom services
COPY common/jupyter-hub.service /etc/systemd/system/

# others
COPY common/lyoko.sudo /etc/sudoers.d/lyoko
COPY common/modules /opt/modules
COPY common/module-path.sh /etc/profile.d/z99-module-path.sh
COPY common/jupyter-settings-overrides.json /opt/jupyterhub/share/jupyter/lab/settings/overrides.json
COPY --from=build-slurm /opt/doc /usr/share/nginx/html/doc

RUN mkdir -pv /var/spool/slurmctld \
    && mkdir -pv /var/spool/slurmd \
    && ln -sf /lib/systemd/system/multi-user.target /etc/systemd/system/default.target \
    && rm -vf /etc/systemd/system/multi-user.target.wants/slurmctld.service /etc/systemd/system/multi-user.target.wants/slurmd.service /etc/systemd/system/multi-user.target.wants/slurmdbd.service /etc/systemd/system/multi-user.target.wants/slurmrestd.service /etc/systemd/system/multi-user.target.wants/nginx.service /etc/systemd/system/multi-user.target.wants/sackd.service /etc/systemd/system/multi-user.target.wants/jupyter-hub.service \
    && rm -f /etc/systemd/system/systemd-logind.service

ENTRYPOINT [ "/opt/local/entrypoint.sh" ]