FROM rockylinux/rockylinux:8 as build
COPY build-el/build-slurm-rpm.sh ./
COPY slurm ./slurm-src
RUN ./build-slurm-rpm.sh

FROM rockylinux/rockylinux:8
COPY --from=build /opt/slurm-repo /opt/slurm-repo
COPY --from=build /etc/yum.repos.d/slurm.repo /etc/yum.repos.d/slurm.repo
COPY build-el/install-packages.sh common/config-task.sh ./
RUN ./install-packages.sh && ./config-task.sh

# Copy files to /etc/slurm/
COPY --chown=slurm:slurm common/slurm.conf common/cgroup.conf common/slurm-init.sh /etc/slurm/

# slurm related files
COPY common/slurmctld-extra.conf common/service-restart.conf /etc/systemd/system/slurmctld.service.d/
COPY common/slurmdbd-extra.conf common/service-restart.conf /etc/systemd/system/slurmdbd.service.d/
COPY common/slurmd-extra.conf common/service-restart.conf /etc/systemd/system/slurmd.service.d/
COPY common/slurmd-env /etc/sysconfig/slurmd

# Jupyter Hub files
COPY common/jupyterhub_config.py /opt/jupyterhub/etc/jupyterhub/
COPY common/service-restart.conf /etc/systemd/system/jupyter-hub.service.d/

# custom services
COPY common/slurm-init.service common/jupyter-hub.service /etc/systemd/system/

# sudoer
COPY common/lyoko.sudo /etc/sudoers.d/lyoko

RUN create-munge-key \
    && mkdir -pv /var/spool/slurmctld \
    && mkdir -pv /var/spool/slurmd \
    && ln -s /usr/lib/systemd/system/{munge,slurmctld,slurmd,slurmdbd,slurm-init}.service /etc/systemd/system/jupyter-hub.service /etc/systemd/system/multi-user.target.wants/ \
    && rm -f /etc/systemd/system/systemd-logind.service

ENTRYPOINT [ "/sbin/init" ]