FROM rockylinux/rockylinux:8 as build
COPY build-slurm-rpm.sh ./
COPY slurm ./slurm-src
RUN ./build-slurm-rpm.sh

FROM rockylinux/rockylinux:8
COPY --from=build /opt/slurm-repo /opt/slurm-repo
COPY --from=build /etc/yum.repos.d/slurm.repo /etc/yum.repos.d/slurm.repo
COPY install-packages.sh .
RUN ./install-packages.sh

# Copy files to /etc/slurm/
COPY --chown=slurm:slurm slurm.conf cgroup.conf slurm-init.sh /etc/slurm/

# slurmctld related files
COPY slurmctld-extra.conf service-restart.conf /etc/systemd/system/slurmctld.service.d/

# slurmdbd  related files
COPY slurmdbd-extra.conf service-restart.conf /etc/systemd/system/slurmdbd.service.d/

# slurmd    related files
COPY slurmd-extra.conf service-restart.conf /etc/systemd/system/slurmd.service.d/
COPY slurmd-env /etc/sysconfig/slurmd

COPY slurm-init.service /etc/systemd/system/
COPY lyoko.sudo /etc/sudoers.d/lyoko

# jupyterlab services
# COPY jupyter-lab.service /etc/systemd/system/
# COPY service-restart.conf /etc/systemd/system/jupyter-lab.service.d/
COPY jupyterhub_config.py /opt/jupyterhub/etc/jupyterhub/
COPY jupyter-hub.service /etc/systemd/system/
COPY service-restart.conf /etc/systemd/system/jupyter-hub.service.d/

RUN create-munge-key \
    && mkdir -pv /var/spool/slurmctld \
    && mkdir -pv /var/spool/slurmd \
    && ln -s /usr/lib/systemd/system/{munge,slurmctld,slurmd,slurmdbd,slurm-init}.service /etc/systemd/system/jupyter-hub.service /etc/systemd/system/multi-user.target.wants/ \
    && rm -f /etc/systemd/system/systemd-logind.service

ENTRYPOINT [ "/sbin/init" ]